### ISSUE TITLE
Исправить ошибку

### ISSUE THREAD

**Issue by Kasiwadzaki** [AlexanderIab/TestTaskJob#1]
Добрый день, меня зовут Вадим, я представитель Uno-Soft.  
  
В вашем алгоритме есть ошибка. Падает на вот этом файле https://github.com/PeacockTeam/new-job/blob/master/lng.7z 
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: index 0, length 0
	at java.base/java.lang.String.checkIndex(String.java:3715)
	at java.base/java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:362)
	at java.base/java.lang.StringBuilder.charAt(StringBuilder.java:85)
	at com.iablonski.Test.extractColumns(Test.java:154)
	at com.iablonski.Test.main(Test.java:29)
```

**Comment by AlexanderIab** [comment]
Добрый день, Вадим 
Хм, у меня алгоритм отработал.
Number of groups with more than one element: 1446
Execution Time: 3.865 seconds

Но, ошибка и правда будет. если строка пустая, добавил проверку при чтении строки.
@Kasiwadzaki
